# Generated by Django 4.2.2 on 2023-06-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='user',
        ),
    ]
