# Generated by Django 4.2.2 on 2023-06-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_player_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['played', 'score'], 'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
        migrations.AddField(
            model_name='player',
            name='played',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Played'),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Score'),
        ),
    ]
